/// <reference types="node"/>
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const banks = [
  "ABHYUDAYA CO-OP BANK LTD",
  "AIRTEL PAYMENTS BANK",
  "ALLAHABAD BANK",
  "AMRELI JILLA MADHYASTHA SAHAKARI BANK L., AMRELI",
  "ANDHRA",
  "APNA SAHAKARI BANK LTD",
  "ARYAVART BANK",
  "AU SMALL FINANCE BANK",
  "AXIS BANK",
  "BANDHAN",
  "BANDHAN BANK",
  "BANK OF BARODA",
  "BANK OF INDIA",
  "BANK OF INDIA ARYAVART BANK",
  "BANK OF MAHARASHTRA",
  "BARODA GUJARAT GRAMIN BANK",
  "BARODA RAJASTHAN GRAMIN BANK",
  "BARODA RAJASTHAN KSHETRIYA GRAMIN BANK",
  "BARODA UTTAR PRADESH GRAMIN BANK",
  "BASSEIN CATHOLIC CO-OP BANK LTD",
  "BIHAR GRAMIN BANK",
  "CANARA BANK",
  "CATHOLIC SYRIAN BANK LTD",
  "CENTRAL BANK OF INDIA",
  "CHHATTISGARH RAJYA GRAMIN BANK",
  "CITY UNION BANK",
  "CORPORATION BANK",
  "DAKSHIN BIHAR GRAMIN BANK",
  "DBS BANK",
  "DCB BANK",
  "DENA BANK",
  "DOMBIVLI NAGARI SAHAKARI BANK LTD",
  "ESAF SMALL FINANCE BANK",
  "ESAF SMALL FINANCE BANK LIMITED",
  "FINCARE SMALL FINANCE BANK LTD",
  "FINO PAYMENTS BANK",
  "GRAMIN BANK OF ARYAVART",
  "HDFC BANK",
  "HIMACHAL PRADESH GRAMIN BANK",
  "ICICI BANK",
  "IDBI BANK",
  "IDBI BANK LTD, CHAMOLI ZILA SAHKARI BANK LIMITED",
  "IDFC FIRST BANK",
  "IDFC FIRST BANK LTD",
  "INDIA POST PAYMENT BANK",
  "INDIAN BANK",
  "INDIAN OVERSEAS BANK",
  "INDIA POST PAYMENT BANK",
  "INDUSIND BANK",
  "JAMMU AND KASHMIR BANK",
  "JAMMU AND KASHMIR BANK LTD, GRAMEEN BANK",
  "JAMMU RURAL BANK",
  "JIO PAYMENTS BANK LIMITED",
  "THE KALUPUR COMMERCIAL CO. OP. BANK LTD.",
  "KARNATAKA BANK",
  "KARUR VYASA BANK LIMITED",
  "KASHI GOMTI SAMYUT GRAMIN BANK",
  "KOTAK MAHINDRA BANK",
  "KRISHNA SAHAKARI BANK LTD",
  "MADHYA BHARAT GRAMIN BANK",
  "MADHYA BIHAR GRAMIN BANK",
  "MADHYA PRADESH GRAMIN BANK",
  "MADHYA PRADESH RAJYA SAHAKARI BANK MARYADIT",
  "MADHYANCHAL GRAMIN BANK",
  "NAINITAL BANK LIMITED",
  "NARMADA JHABUA GRAMIN BANK",
  "NEW INDIA BANK",
  "NORTH EAST SMALL FINANCE BANK LIMITED",
  "NSDL PAYMENTS BANK",
  "ORIENTAL BANK OF COMMERCE",
  "PAYTM PAYMENT BANK",
  "PRIME CO-OP BANK LTD",
  "PUNJAB & SIND BANK",
  "PUNJAB AND SIND BANK",
  "PUNJAB AND SINDH BANK",
  "PUNJAB GRAMIN BANK",
  "PUNJAB NATIONAL BANK",
  "PURVANCHAL GRAMIN BANK",
  "RAJASTHAN MARUDHARA GRAMIN BANK",
  "RAJKOT NAGARIK SAHAKARI BANK LTD",
  "RATNAKAR BANK LTD",
  "RBL BANK",
  "SARASWAT CO-OPERATIVE BANK LTD",
  "SARVA HARYANA GRAMIN BANK",
  "SARVA U P GRAMIN BANK",
  "SARVODAYA SAHAKARI BANK LTD",
  "SAURASHTRA GRAMIN BANK",
  "SHARDA GRAMIN BANK",
  "SHRI VEERSHAIV CO OP BANK LTD",
  "SLICE SMALL FINANCE BANK",
  "SOUTH INDIAN BANK",
  "STATE BANK OF BIKANER AND JAIPUR",
  "STATE BANK OF INDIA",
  "STATE BANK OF INDIA, MADHYA BHARAT GRAMIN BANK",
  "STATE BANK OF INDIA, PURVANCHAL GRAMIN BANK",
  "STATE BANK OF INDIA, UTTARANCHAL GRAMIN BANK",
  "STATE BANK OF INDIA, VANANCHAL GRAMIN BANK",
  "STATE BANK OF MAURITIUS LTD",
  "SURAT DISTRICT CO-OP BANK LTD",
  "SURAT NATIONAL CO-OP BANK LTD",
  "SURYODAY SMALL FINANCE BANK LIMITED",
  "SYNDICATE BANK",
  "THE FEDERAL BANK LTD",
  "THE GUJARAT STATE CO-OPERATIVE BANK LTD",
  "THE JAMMU AND KASHMIR BANK LTD",
  "THE LUNAWADA NAGRIK SAHAKARI BANK LTD",
  "THE SURAT PEOPLES CO-OP BANK LTD",
  "THE ZOROASTRIAN CO-OP BANK LTD",
  "TKCCBL",
  "TSDCBL",
  "UCO BANK",
  "UJJIVAN SMALL FINANCE BANK LIMITED",
  "UNION BANK OF INDIA",
  "UNITED BANK OF INDIA",
  "UTKARSH SMALL FINANCE BANK",
  "UTTAR BIHAR GRAMIN BANK",
  "UTTARAKHAND GRAMIN BANK",
  "UTTARANCHAL GRAMIN BANK",
  "VASAI VIKAS SAHAKARI BANK LTD",
  "VIJAYA BANK",
  "YES BANK",
];

async function main() {
  console.log(`Start seeding banks...`);

  for (const bankName of banks) {
    const bank = await prisma.bank.upsert({
      where: { name: bankName },
      update: {}, // Do nothing if it already exists
      create: {
        name: bankName,
        isActive: true,
      },
    });
    console.log(`Verified/Created bank: ${bank.name}`);
  }

  console.log(`Seeding finished successfully.`);
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });